### ISSUE TITLE
encodeHeaderAsRLP mixHash and nonce

### ISSUE THREAD

**Issue by SoujanyaPonnapalli** [RainBlock/ethereum-block#5]
encodeHeaderAsRlp returns different values for mixHash and nonce while rlp encoding block headers:

For encoding the genesisBlock header:
Expected:
```
mixHash:  <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>,
nonce:  <Buffer 00 00 00 00 00 00 00 42> 
```
Received:
```
mixHash:  <Buffer >,
nonce:  <Buffer 42> 
```

**Comment by no2chem** [comment]
Sure. I'll push a PR.

More succinctly, mixHash should always be 32 bytes and nonce should always be 8.
